### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by AbdullahSH2004** [venaxyt/mysterium#12]
BRO MAKE IT SUPPORT LINUX PATH!!!

Traceback (most recent call last):                                                                                                                                      
  File "/home/abdullahsh/Desktop/fucking/mysterium/mysterium.py", line 202, in <module>                                                                                 
    modules.blue.Blue(f'modules\\{uninspected_file_name}.{uninspected_file_extension}', uninspected_file_directory)                                                     
  File "/home/abdullahsh/Desktop/fucking/mysterium/modules/blue.py", line 39, in __init__                                                                               
    self.reading_file()                                                                                                                                                 
  File "/home/abdullahsh/Desktop/fucking/mysterium/modules/blue.py", line 95, in reading_file                                                                           
    with open(self.filePath, 'rb') as f:                                                                                                                                
FileNotFoundError: [Errno 2] No such file or directory: 'modules\\uninspected.pyc'

**Comment by venaxyt** [comment]
In fact, a contributor made it functional running under Linux, try to fix it yourself if there is something wrong because I am not on Linux but on Windows.
