### ISSUE TITLE
TypeError when trying to inspect file

### ISSUE THREAD

**Issue by Nqndi** [venaxyt/mysterium#2]
The following error pops up when I try to inspect a file:

  [>] Enter uninspected file directory : C:\Users\Erk\Desktop\reverse\TheRigsNitro.exe_extracted\grabitbitch.pyc

import re
import json
re.escape($)
Traceback (most recent call last):
  File "grabitbitch.py", line 10, in <module>
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\email\_policybase.py", line 7, in <module>
    from email import header
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\email\header.py", line 16, in <module>
    import email.quoprimime
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\email\quoprimime.py", line 44, in <module>
    from string import ascii_letters, digits, hexdigits
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\string.py", line 146, in <module>
    Template.__init_subclass__()
  File "C:\Users\Erk\AppData\Local\Programs\Python\Python39\lib\string.py", line 85, in __init_subclass__
    cls.pattern = _re.compile(pattern, cls.flags | _re.VERBOSE)
TypeError: unsupported operand type(s) for |: 'str' and 'str'

  [>] The code is finished, don't forget to follow @venaxyt and @IDRALOU on Github

**Comment by venaxyt** [comment]
I will fix this error on next updates don't worry about that, you can even fix it by yourself by editing the requests module.

**Comment by BrieflyX** [comment]
So are there any ideas about how to solve this exception?
