### ISSUE TITLE
ValueError: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by 2Craft** [venaxyt/mysterium#34]
import re
import re
re.sub(\s+, , DB7C 2ABF62E3 5E668076 BEAD208B)
Traceback (most recent call last):
  File "<modules\BTC.py>", line 2, in <module>
  File "<frozen BTC>", line 7, in <module>
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python38\lib\site-packages\bip32utils\__init__.py", line 1, in <module>
    from bip32utils.BIP32Key import BIP32Key, BIP32_HARDEN
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python38\lib\site-packages\bip32utils\BIP32Key.py", line 10, in <module>
    import ecdsa
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python38\lib\site-packages\ecdsa\__init__.py", line 4, in <module>
    from .keys import (
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python38\lib\site-packages\ecdsa\keys.py", line 76, in <module>
    from . import ecdsa
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python38\lib\site-packages\ecdsa\ecdsa.py", line 311, in <module>
    _p = int(remove_whitespace("DB7C 2ABF62E3 5E668076 BEAD208B"), 16)
ValueError: invalid literal for int() with base 16: ''

**Comment by venaxyt** [comment]
I can do nothing about this since the error comes from you, from the ecdsa module.
Maybe different versions of it were used on the program's creator computer and on yours.
