### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'str' and 'str'

### ISSUE THREAD

**Issue by makarworld** [venaxyt/mysterium#38]
[>] Enter uninspected file path : contract_module.pyc

```
import re
import re
re.escape($)
Traceback (most recent call last):
  File "./mechanism/contract_module.py", line 1, in <module>
  File "C:\Python38\lib\site-packages\web3\__init__.py", line 4, in <module>
    import pkg_resources
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 33, in <module>
    import email.parser
  File "C:\Python38\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Python38\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Python38\lib\email\_policybase.py", line 7, in <module>
    from email import header
  File "C:\Python38\lib\email\header.py", line 16, in <module>
    import email.quoprimime
  File "C:\Python38\lib\email\quoprimime.py", line 44, in <module>
    from string import ascii_letters, digits, hexdigits
  File "C:\Python38\lib\string.py", line 80, in <module>
    class Template(metaclass=_TemplateMetaclass):
  File "C:\Python38\lib\string.py", line 77, in __init__
    cls.pattern = _re.compile(pattern, cls.flags | _re.VERBOSE)
TypeError: unsupported operand type(s) for |: 'str' and 'str'
```

  [>] The code is finished

**Comment by venaxyt** [comment]
Delete the re.py file from /modules folder and try again, the error will be gone.
