### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by 2Craft** [venaxyt/mysterium#41]
Traceback (most recent call last):
  File "C:\Users\123\Downloads\Telegram Desktop\BTC@mining_20_bot v6.1\BTC@mining_20_bot v6.1\Bip39Gen.py", line 2, in <module>
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python39\lib\secrets.py", line 19, in <module>
    from random import SystemRandom
ImportError: cannot import name 'SystemRandom' from 'random' (E:\DEMO\mysterium-main\modules\random.py)

**Comment by venaxyt** [comment]
Just delete re.py from /modules folder and run it again.
