### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by Zinovich** [venaxyt/mysterium#8]
Traceback (most recent call last):
  File "mysterium.py", line 202, in <module>
    modules.blue.Blue(f'modules\\{uninspected_file_name}.{uninspected_file_extension}', uninspected_file_directory)
  File "C:\Users\windows\OneDrive\Images\skid detector\antiskidding room (file)\mysterium-main\modules\blue.py", line 43, in __init__
    self.execute_file()
  File "C:\Users\windows\OneDrive\Images\skid detector\antiskidding room (file)\mysterium-main\modules\blue.py", line 173, in execute_file
    exec(self.content, globals(), self.variables)
ValueError: source code string cannot contain null bytes

**Comment by venaxyt** [comment]
It is because your main file is empty or because you didn't imported all it's extracted modules.
